---

- name: install proftpd
  apt:
    name: proftpd-basic
    state: present
    install_recommends: false
    update_cache:       true

- name: mkdir /srv/ftp
  file:
    path: "{{ PRO_DIR  }}"
    owner: ftp
    group: nogroup
    state: directory

- name: change usermod
  command: usermod -d {{ PRO_DIR  }} ftp

- name: mkdir /home/ftpuser
  file:
    path: "{{ PRO_VIR_DIR  }}"
    owner: "{{ PRO_UID }}"
    group: "{{ PRO_GID }}"
    mode: "{{ PRO_LIMIT }}"
    state: directory

- name: mkdir /usr/local/etc/proftpd
  file: 
    path: "{{ PRO_FTPASSWD_DIR }}"
    state: directory

- name: ftpasswd user
  shell: echo {{ PRO_VIRTUAL_PASS  }} | ftpasswd --passwd --file={{ PRO_PASSWD_DIR }} --name={{ PRO_VIRTUAL_USER }} --uid={{ PRO_UID }} --home={{ PRO_VIR_DIR }} --shell=/bin/false --stdin

- name: ftpasswd group
  shell: ftpasswd --file={{ PRO_GROUP_DIR }} --group --name={{ PRO_GROUP_NAME }} --gid={{ PRO_GID }}

- name: user add to group
  shell: ftpasswd --group --name={{ PRO_GROUP_NAME }} --gid={{ PRO_GID }} --member={{ PRO_VIRTUAL_USER }} --file={{ PRO_GROUP_DIR }}
